# Generated by Django 3.1.4 on 2020-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checksite', '0003_site_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ip_adress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
