# Generated by Django 3.1.4 on 2020-12-13 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checksite', '0005_auto_20201211_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
